[tool.poetry]
name = "mnmnwag"
version = "3.1"
description = ""
authors = ["Matthew Newton <matthewn@alum.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.2"
wagtail = "^2.10"
django-dbbackup = "^3.3.0"
django-debugtools = "*"
django-extensions = "*"
werkzeug = "*"
python-dateutil = "*"
django-compressor = "*"
django-libsass = "*"
django-capture-tag = "*"
django-typogrify = "*"
django-comments-xtd = "*"
django-debug-toolbar = "*"
django-markdown2 = "*"
psycopg2 = "*"
wagtail-cache = "*"
wagtailmedia = "*"
comments_wagtail_xtd = "*"
tweepy = "*"
django-cachalot = "*"
django-browser-reload = "*"
pywatchman = "*"
stopforumspam = "*"
django-honeypot = "*"
pyexiv2 = "^2.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
