[tool.poetry]
name = "mnmnwag"
version = "3.1"
description = ""
authors = ["Matthew Newton <matthewn@alum.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "*"
wagtail = "*"
django-dbbackup = {url = "https://github.com/jazzband/django-dbbackup/archive/refs/tags/4.0.0rc1.tar.gz"}
django-debugtools = "*"
django-extensions = "*"
werkzeug = "*"
python-dateutil = "*"
django-compressor = "*"
django-libsass = "*"
django-capture-tag = "*"
django-comments-xtd = "*"
django-debug-toolbar = "*"
django-markdown2 = "*"
psycopg2 = "*"
wagtailmedia = "*"
tweepy = "*"
django-cachalot = "*"
django-browser-reload = "*"
pywatchman = "*"
django-honeypot = "*"
pyexiv2 = "*"
gunicorn = "*"
setproctitle = "*"
seevooplay = "*"
django-antispam = "*"
django-crequest = "*"
django-typogrify = {url = "https://github.com/matthewn/django-typogrify/archive/refs/tags/v2.0.tar.gz"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
