[tool.poetry]
name = "mnmnwag"
version = "1.2"
description = ""
authors = ["Matthew Newton <matthewn@alum.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "*"
wagtail = "^2.10"
django-dbbackup = "4.0.0b0"
django-debugtools = "*"
django-extensions = "*"
werkzeug = "*"
python-dateutil = "*"
django-compressor = "*"
django-libsass = "*"
django-capture-tag = "*"
django-comments-xtd = "*"
django-debug-toolbar = "*"
django-markdown2 = "*"
psycopg2 = "*"
wagtail-cache = "*"
wagtailmedia = "*"
tweepy = "*"
django-cachalot = "*"
django-browser-reload = "*"
pywatchman = "*"
django-honeypot = "*"
pyexiv2 = "^2.7.1"
smartypants = "^2.0.1"
wagtailfontawesome = "^1.2.1"
num2words = "^0.5.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
