[tool.poetry]
name = "mnmnwag"
version = "3.1"
description = ""
authors = ["Matthew Newton <matthewn@alum.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "*"
wagtail = "*"
django-dbbackup = "*"
django-debugtools = "*"
django-extensions = "*"
werkzeug = "*"
python-dateutil = "*"
django-compressor = "*"
django-libsass = "*"
django-capture-tag = "*"
django-typogrify = { git = "https://github.com/matthewn/django-typogrify", branch = "django40" }
django-comments-xtd = "*"
django-debug-toolbar = "*"
django-markdown2 = "*"
psycopg2 = "*"
wagtailmedia = "*"
comments_wagtail_xtd = "*"
tweepy = "*"
django-cachalot = "*"
django-browser-reload = "*"
pywatchman = "*"
django-honeypot = "*"
pyexiv2 = "^2.7.1"
gunicorn = "^20.1.0"
setproctitle = "^1.2.2"
seevooplay = "^1.0.5"
django-antispam = "^1.0.3"
django-crequest = "^2018.5.11"
num2words = "^0.5.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
