[tool.poetry]
name = "mnmnwag"
version = "0.1.0"
description = ""
authors = ["Matthew Newton <matthewn@alum.berkeley.edu>"]

[tool.poetry.dependencies]
python = "^3.6"
django = "*"
wagtail = "^2.10"
django-dbbackup = "^3.3.0"
django-debugtools = "^1.8"
django-extensions = "^3.0.5"
werkzeug = "^1.0.1"
python-dateutil = "^2.8.1"
django-compressor = "^2.4"
django-libsass = "^0.8"
django-capture-tag = "^1.0"
django-typogrify = "^1.3.3"
django-comments-xtd = "^2.7.1"
django-debug-toolbar = "^2.2"
django-markdown2 = "^0.3.1"
psycopg2 = "^2.8.5"
wagtail-cache = "^1.0.1"
wagtailmedia = "^0.6.0"
comments_wagtail_xtd = "^1.0.1"
tweepy = "^4.3.0"
django-cachalot = "^2.4.4"
django-browser-reload = "^1.0.0"
pywatchman = "^1.4.1"
stopforumspam = "^1.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
