# Generated by Django 2.2.11 on 2020-03-28 20:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('mnmnwag', '0002_blogindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wagtailcore.Page')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnmnwag_posttag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='modernposttag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='modernposttag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='legacypost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mnmnwag.PostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='modernpost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='mnmnwag.PostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='LegacyPostTag',
        ),
        migrations.DeleteModel(
            name='ModernPostTag',
        ),
    ]
