# Generated by Django 2.2.11 on 2020-04-26 01:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0003_auto_20200328_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='page_message',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complexpage',
            name='page_message',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
