# Generated by Django 2.2.15 on 2020-08-31 00:43

from django.db import migrations
import mnmnwag.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0011_auto_20200826_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['ol', 'ul', 'blockquote', 'bold', 'italic', 'superscript', 'subscript', 'strikethrough', 'code', 'link', 'image', 'document-link'])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.blocks.CharBlock(max_length=256, required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('media', mnmnwag.blocks.MediaBlock(icon='media')), ('raw_HTML', wagtail.blocks.RawHTMLBlock(required=False))]),
        ),
        migrations.AlterField(
            model_name='modernpost',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['ol', 'ul', 'blockquote', 'bold', 'italic', 'superscript', 'subscript', 'strikethrough', 'code', 'link', 'image', 'document-link'])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.blocks.CharBlock(max_length=256, required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('media', mnmnwag.blocks.MediaBlock(icon='media')), ('raw_HTML', wagtail.blocks.RawHTMLBlock(required=False))]),
        ),
    ]
