# Generated by Django 3.1.5 on 2021-01-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0015_tagdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacypost',
            name='old_path',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legacypost',
            name='body',
            field=models.TextField(),
        ),
    ]
