# Generated by Django 3.2.9 on 2021-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0020_tweetstracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernpost',
            name='tweet_title',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
