# Generated by Django 3.2.11 on 2022-01-21 22:28

from django.db import migrations
import mnmnwag.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0021_modernpost_tweet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modernpost',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('teaser', wagtail.core.blocks.RichTextBlock(features=['ol', 'ul', 'blockquote', 'bold', 'italic', 'superscript', 'subscript', 'strikethrough', 'code', 'link', 'image', 'document-link'])), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['ol', 'ul', 'blockquote', 'bold', 'italic', 'superscript', 'subscript', 'strikethrough', 'code', 'link', 'image', 'document-link'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.core.blocks.CharBlock(max_length=256, required=False)), ('link', wagtail.core.blocks.URLBlock(required=False)), ('float', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[(3, 'None'), (1, 'Left'), (2, 'Right')])), ('zoom', wagtail.core.blocks.ChoiceBlock(choices=[(0, 'Off'), (1, 'On')]))])), ('slides', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.core.blocks.CharBlock(max_length=256, required=False))])))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('media', mnmnwag.blocks.MediaBlock(icon='media')), ('raw_HTML', wagtail.core.blocks.RawHTMLBlock(required=False))]),
        ),
    ]
