# Generated by Django 3.2.12 on 2022-03-12 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0022_alter_modernpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommedia',
            name='duration',
            field=models.FloatField(blank=True, default=0, help_text='Duration in seconds', validators=[django.core.validators.MinValueValidator(0)], verbose_name='duration'),
        ),
    ]
