# Generated by Django 3.2.12 on 2022-03-12 23:28

from django.db import migrations, models
import django.db.models.deletion
import mnmnwag.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('mnmnwag', '0023_alter_custommedia_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['blockquote', 'bold', 'italic', 'superscript', 'subscript', 'strikethrough', 'link', 'image', 'document-link'])), ('slides', wagtail.core.blocks.StructBlock([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.core.blocks.CharBlock(max_length=256, required=False))])))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('media', mnmnwag.blocks.MediaBlock(icon='media')), ('raw_HTML', wagtail.core.blocks.RawHTMLBlock(required=False))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
