# Generated by Django 3.2.12 on 2022-03-12 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('mnmnwag', '0024_gallerypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='common_alt_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='common_caption',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='import_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection'),
        ),
    ]
