# Generated by Django 3.2.12 on 2022-03-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('mnmnwag', '0025_auto_20220312_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='import_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection'),
        ),
    ]
