# Generated by Django 3.2.12 on 2022-03-13 06:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0026_alter_gallerypage_import_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='common_caption',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
