# Generated by Django 3.2.12 on 2022-03-26 05:47

from django.db import migrations
import mnmnwag.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mnmnwag', '0028_auto_20220319_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h3', 'h4', 'h5', 'ol', 'ul', 'blockquote', 'bold', 'italic', 'superscript', 'subscript', 'strikethrough', 'code', 'link', 'image', 'document-link'])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.blocks.CharBlock(max_length=256, required=False)), ('link', wagtail.blocks.URLBlock(required=False)), ('float', wagtail.blocks.ChoiceBlock(blank=False, choices=[(3, 'None'), (1, 'Left'), (2, 'Right')])), ('zoom', wagtail.blocks.ChoiceBlock(choices=[(0, 'Off'), (1, 'On')]))])), ('slides', wagtail.blocks.StructBlock([('slides', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('alt_text', wagtail.blocks.CharBlock(max_length=256, required=False))])))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('media', mnmnwag.blocks.MediaBlock(icon='media')), ('raw_HTML', wagtail.blocks.RawHTMLBlock(required=False)), ('danger', wagtail.blocks.RawHTMLBlock(label='DANGER!', required=False))]),
        ),
    ]
