# Generated by Django 4.1.1 on 2022-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0032_alter_posttag_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="modernpost",
            name="do_not_tweet",
            field=models.BooleanField(
                default=False,
                help_text="Do not automatically generate a tweet about this post.",
                verbose_name="Do not tweet",
            ),
        ),
    ]
