# Generated by Django 5.0.9 on 2024-11-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0038_alter_complexpage_body_alter_gallerypage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
