# Generated by Django 5.1.6 on 2025-02-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0040_alter_complexpage_body_alter_modernpost_body"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TweetsTracker",
            new_name="TootsTracker",
        ),
        migrations.AlterModelOptions(
            name="tootstracker",
            options={"verbose_name_plural": "Toots job tracker"},
        ),
    ]
