# Generated by Django 5.1.6 on 2025-02-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0042_remove_modernpost_do_not_tweet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modernpost",
            name="toot_this",
            field=models.BooleanField(
                default=False,
                help_text="Automatically generate a toot about this post.",
                verbose_name="Toot this",
            ),
        ),
    ]
