# Generated by Django 5.2.1 on 2025-06-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0043_alter_modernpost_toot_this"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custommedia",
            options={"verbose_name": "media", "verbose_name_plural": "media items"},
        ),
    ]
