# Generated by Django 5.2.5 on 2025-08-12 22:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0044_alter_custommedia_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slogan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", wagtail.fields.RichTextField()),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
