# Generated by Django 5.2.5 on 2025-08-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0045_slogan"),
    ]

    operations = [
        migrations.AddField(
            model_name="slogan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
