# Generated by Django 5.2.14 on 2026-05-16 17:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0049_alter_complexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 8),
                    ("slides", 11),
                    ("embed", 12),
                    ("media", 13),
                    ("raw_HTML", 14),
                    ("danger", 15),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "blockquote",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "kbd",
                                "code",
                                "link",
                                "image",
                                "document-link",
                                "footnotes",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": False,
                            "choices": [(3, "None"), (1, "Left"), (2, "Right")],
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(0, "Off"), (1, "On")]},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("link", 5),
                                ("float", 6),
                                ("zoom", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alt_text", 4)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("slides", 10)]], {}),
                    12: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    13: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    14: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "DANGER!", "required": False},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="gallerypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("slides", 7),
                    ("embed", 8),
                    ("media", 9),
                    ("raw_HTML", 10),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "blockquote",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "link",
                                "image",
                                "document-link",
                                "footnotes",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alt_text", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: ("wagtail.blocks.StructBlock", [[("slides", 6)]], {}),
                    8: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    9: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    10: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="modernpost",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("teaser", 1),
                    ("paragraph", 1),
                    ("image", 8),
                    ("slides", 11),
                    ("embed", 12),
                    ("media", 13),
                    ("raw_HTML", 14),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "ol",
                                "ul",
                                "blockquote",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "kbd",
                                "code",
                                "footnotes",
                                "link",
                                "image",
                                "document-link",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": False,
                            "choices": [(3, "None"), (1, "Left"), (2, "Right")],
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(0, "Off"), (1, "On")]},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("link", 5),
                                ("float", 6),
                                ("zoom", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3), ("alt_text", 4)]],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("slides", 10)]], {}),
                    12: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    13: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    14: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                },
            ),
        ),
    ]
