# Generated by Django 5.2.15 on 2026-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnmnwag", "0050_alter_complexpage_body_alter_gallerypage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complexpage",
            name="constrict_content_width",
            field=models.BooleanField(
                default=False,
                help_text="Constrict the content area to a comfortable width for reading.",
            ),
        ),
        migrations.AddField(
            model_name="complexpage",
            name="show_page_title",
            field=models.BooleanField(
                default=False,
                help_text="Make the <h2> page title visible on this page.",
            ),
        ),
    ]
