# Generated by Django 5.2.14 on 2026-05-16 17:54

import wagtail.blocks.field_block
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("madprops", "0013_homepagebannermessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivespage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 8),
                    ("embed", 9),
                    ("media", 10),
                    ("raw_HTML", 11),
                    ("danger", 12),
                    ("prop", 18),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "blockquote",
                                "yes",
                                "no",
                                "bold",
                                "italic",
                                "strikethrough",
                                "code",
                                "footnotes",
                                "link",
                                "image",
                                "document-link",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": False,
                            "choices": [(3, "None"), (1, "Left"), (2, "Right")],
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(0, "Off"), (1, "On")]},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("link", 5),
                                ("float", 6),
                                ("zoom", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    10: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    11: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "DANGER!", "required": False},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (wagtail.blocks.field_block.URLBlock,),
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("yes", "Yes"),
                                ("no", "No"),
                                ("nopos", "No position"),
                                ("noadv", "No position (advisory measure)"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("approved", "Approved"),
                                ("rejected", "Rejected"),
                            ],
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("paragraph", 1),
                                ("image", 8),
                                ("embed", 9),
                                ("media", 10),
                                ("raw_HTML", 11),
                                ("danger", 12),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("prop_number", 13),
                                ("prop_title", 13),
                                ("info_links", 14),
                                ("recommendation", 15),
                                ("result", 16),
                                ("writeup", 17),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="editionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 8),
                    ("embed", 9),
                    ("media", 10),
                    ("raw_HTML", 11),
                    ("danger", 12),
                    ("prop", 18),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "blockquote",
                                "yes",
                                "no",
                                "bold",
                                "italic",
                                "strikethrough",
                                "code",
                                "footnotes",
                                "link",
                                "image",
                                "document-link",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": False,
                            "choices": [(3, "None"), (1, "Left"), (2, "Right")],
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(0, "Off"), (1, "On")]},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("link", 5),
                                ("float", 6),
                                ("zoom", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    10: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    11: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "DANGER!", "required": False},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (wagtail.blocks.field_block.URLBlock,),
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("yes", "Yes"),
                                ("no", "No"),
                                ("nopos", "No position"),
                                ("noadv", "No position (advisory measure)"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("approved", "Approved"),
                                ("rejected", "Rejected"),
                            ],
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("paragraph", 1),
                                ("image", 8),
                                ("embed", 9),
                                ("media", 10),
                                ("raw_HTML", 11),
                                ("danger", 12),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("prop_number", 13),
                                ("prop_title", 13),
                                ("info_links", 14),
                                ("recommendation", 15),
                                ("result", 16),
                                ("writeup", 17),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepagebannermessage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 8),
                    ("embed", 9),
                    ("media", 10),
                    ("raw_HTML", 11),
                    ("danger", 12),
                    ("prop", 18),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "blockquote",
                                "yes",
                                "no",
                                "bold",
                                "italic",
                                "strikethrough",
                                "code",
                                "footnotes",
                                "link",
                                "image",
                                "document-link",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": False,
                            "choices": [(3, "None"), (1, "Left"), (2, "Right")],
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(0, "Off"), (1, "On")]},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("link", 5),
                                ("float", 6),
                                ("zoom", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    10: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    11: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "DANGER!", "required": False},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (wagtail.blocks.field_block.URLBlock,),
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("yes", "Yes"),
                                ("no", "No"),
                                ("nopos", "No position"),
                                ("noadv", "No position (advisory measure)"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("approved", "Approved"),
                                ("rejected", "Rejected"),
                            ],
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("paragraph", 1),
                                ("image", 8),
                                ("embed", 9),
                                ("media", 10),
                                ("raw_HTML", 11),
                                ("danger", 12),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("prop_number", 13),
                                ("prop_title", 13),
                                ("info_links", 14),
                                ("recommendation", 15),
                                ("result", 16),
                                ("writeup", 17),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 8),
                    ("embed", 9),
                    ("media", 10),
                    ("raw_HTML", 11),
                    ("danger", 12),
                    ("prop", 18),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": [
                                "h3",
                                "h4",
                                "h5",
                                "ol",
                                "ul",
                                "blockquote",
                                "yes",
                                "no",
                                "bold",
                                "italic",
                                "strikethrough",
                                "code",
                                "footnotes",
                                "link",
                                "image",
                                "document-link",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail_footnotes.blocks.RichTextBlockWithFootnotes",
                        (),
                        {
                            "features": ["bold", "italic", "link", "footnotes"],
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If blank, site will attempt to use the image's description.",
                            "max_length": 256,
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": False,
                            "choices": [(3, "None"), (1, "Left"), (2, "Right")],
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(0, "Off"), (1, "On")]},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("caption", 3),
                                ("alt_text", 4),
                                ("link", 5),
                                ("float", 6),
                                ("zoom", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    10: ("mnmnwag.blocks.MediaBlock", (), {"icon": "media"}),
                    11: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"label": "DANGER!", "required": False},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (wagtail.blocks.field_block.URLBlock,),
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("yes", "Yes"),
                                ("no", "No"),
                                ("nopos", "No position"),
                                ("noadv", "No position (advisory measure)"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("approved", "Approved"),
                                ("rejected", "Rejected"),
                            ],
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("paragraph", 1),
                                ("image", 8),
                                ("embed", 9),
                                ("media", 10),
                                ("raw_HTML", 11),
                                ("danger", 12),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("prop_number", 13),
                                ("prop_title", 13),
                                ("info_links", 14),
                                ("recommendation", 15),
                                ("result", 16),
                                ("writeup", 17),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
